---
title: "p8105_hw4_p2"
author: "Ruiwei Zhang"
date: "10/24/2017"
output: 
   html_document:
    toc: true
    toc_float: true
---

```{r getting_ready}
library(tidyverse)
library(haven)
library(janitor)
library(readxl)
library(ggridges)
library(ggthemes)
library(knitr)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

```{r}
pols_month = 
  read.csv("./fivethirtyeight_datasets/pols-month.csv") %>%
  clean_names() %>%
  mutate(mon = as.Date(mon),
         mon = lubridate::floor_date(mon, "month")) %>%
  rename(date = mon)
GDP = 
  read.csv("./fivethirtyeight_datasets/GDP.csv") %>%
  clean_names() %>%
  mutate(date = as.Date(date),
         date = lubridate::floor_date(date, "month"))
combined = 
  full_join(pols_month, GDP, by = "date")
```

#Getting the data ready for plot
```{r}
combined <- as.tibble(combined) %>% 
  filter(!is.na(value)) %>%
  filter(!value == ".") %>%
  mutate(president = ifelse(prez_gop == 1, "Republican", "Democratic")) %>%
  mutate(president = as.factor(president), GDP = as.numeric(value))
```
**Clean the data so that president information are in one row.**  

#Plot the GDP showing the GDP value over time
```{r}
combined %>% ggplot(aes(x = date, y = GDP)) + geom_point(aes(color = president)) + geom_line(aes(color = president)) + labs(title = "GDP value over time from different party president")
combined %>% ggplot(aes(x = date, y = GDP)) + geom_point(aes(color = president)) + geom_line(aes(color = president)) + facet_grid(~president) + labs(title = "GDP value over time from different party president") + theme(legend.position = "bottom")
```

**From the plot, from the plots we can see that the GDP value varies from time to time, and the party of the president doesnt really affect the value. And the values over the years are fluctuating but never drop to very low level.**

